name:                adiram
version:             0.1.0.0
github:              "delreluca/adiram"
license:             BSD3
author:              "Luca Del Re"
maintainer:          "delreluca@googlemail.com"
copyright:           "Copyright 2019 Luca Del Re"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/delreluca/adiram#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

# Following Lexi's opinionated Haskell guide on warnings
# <https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/#warning-flags-for-a-safe-build>

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  adiram-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adiram
    - haskeline

tests:
  adiram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adiram
    - tasty >= 1.2
    - tasty-hunit
